name: Lint, format, and test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.44.4
      - run: deno fmt --check .
    continue-on-error: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.44.4
      - run: deno lint .
    continue-on-error: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.44.4
      - run: deno test
    continue-on-error: true
